spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth?useSSL=false&serverTimezone=UTC
    username: seoin
    password: seoin@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true